### ISSUE TITLE
Call to a member function respond() on null

### ISSUE THREAD

**Issue by khvalov** [maxbeckers/google-actions-php#5]
Hi, i got: 
Error: Call to a member function respond() on null in /Handlers/SimpleRequestHandler.php:33
Any suggestions ? 

following up code you  have 
private $responseHelper;

but it's never defined (no __constructor)

**Comment by maxbeckers** [comment]
Yes you're right, i dont have any constructor there. But it is just an example to show how it could work. The example is not running.
