### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by gonzaloplaza** [maxbeckers/google-actions-php#6]
Hi there. Google does not provide any official PHP SDK for Google Assistant Actions development. Are you know if this code is already working with latest google updates?. 

Thank you in advance.

**Comment by maxbeckers** [comment]
Hi @gonzaloplaza, 

as far as I know, is it working with the newest version. There may be some new features not implemented in this lib, but when you detect some missing features feel free to open an issue.
